volumes:
  mongo_data:

networks:
  backend:

services:
  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:latest
    restart: always
    networks:
      - backend
    env_file: .env
    ports:
      - ${PORT-27017}:27017
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
